[Company]
name=El Guadual de Armenia
address=Carrera 18 calle 20
nit=16247560-5
owner=Marleny Gonzalez
phone=3128251598

[Images]
logo_left=/home/lynx/Documentos/Programas/Parqueadero/Impresora/files/logos/bandera_2.png
logo_right=/home/lynx/Documentos/Programas/Parqueadero/Impresora/files/logos/bandera_2.png

[Normas]
Reglamento=1. La motocicleta se entrega solo al portador de este recibo. 2. Revise su moto antes de salir. No se aceptan reclamos posteriores. 3. No respondemos por objetos dejados en la moto. 4. No aceptamos ordenes escritas ni telefonicas. 5. No somos responsables por perdidas o danos causados por fuerza mayor. 6. El valor se cobra por hora o fraccion. 7. No deje las llaves. Nota: Los danos causados por la moto seran asumidos por su propietario.
